### ISSUE TITLE
The outcome column must be named "value"?

### ISSUE THREAD

**Issue by ichsan2895** [rafzamb/sknifedatar#16]
Hello, I am new with sknifedatar, so I have tried this tutorial:

https://github.com/rafzamb/sknifedatar

But with different dataset which contains outcome column named "_hits_" instead "_value_",

When I tried run this syntax: 
```
model_table_emae = modeltime_multifit(serie = nested_serie %>% head(3),
                                       .prop = 0.8,
                                       m_auto_arima,
                                       m_stlm_arima,
                                       m_nnetar)
```

**Error: Problem with `mutate()` input `m_auto_arima`. x object 'value' not found i Input `m_auto_arima` is `purrr::map(...)`.**

![image](https://user-images.githubusercontent.com/60387342/116216843-42e03680-a773-11eb-959c-65db06258ba1.png)

This problem solved when I changed colnames "_hits_" to "_value_".

**Comment by rafzamb** [comment]
Hi, thank you very much for reporting this. Maybe some restriction and a warning should be added so that the columns of the time series have "date" and "value" names.

**Comment by rafzamb** [comment]
The issue was resolved through the main branch
