### ISSUE TITLE
Multiple Outputs on one tabset

### ISSUE THREAD

**Issue by rodserr** [rafzamb/sknifedatar#8]
It would be nice if `automagic_tabs` could deploy multiple outputs in the same tabset group. This could be a solution #7 . Also, it avoids calling xaringanExtra before automagic_tabs()

**Comment by rafzamb** [comment]
Good idea, very good the elimination of xaringanextra dependency.

Two functions could be generated, automagic_tabs for the simple case and automagic_tabs2 for more complex cases of multiple outputs.

automagic_tabs might need an update to take the parameters of the chunks of type carcater, for example fig.align = 'center', it only works with fig.align = "'center'". You can also test whether it is necessary to leave the control of Sys.time () or if it is feasible to remove it.

what do you think?
